### PR TITLE
Infer analysis - update hypothesis and permutation

### PR DESCRIPTION
**Pull request by carinaya**
Hi guys, I update the hypothesis and permutation for the inferential analysis part. Please kindly look over and free to comment and correct me if I missed or did a mistake. Thanks.

Plus, I found that according to the requirement, we are expected to use qmd instead of rmd, so I replaced the rmd file with qmd file.

### CODE REVIEW

**Comment by Kierst01** [comment]
Hey, I'm wondering if a proportion would be better to answer our question? Since the number of eggs depends on how many hens there are

**Comment by carinaya** [comment]
> Hey, I'm wondering if a proportion would be better to answer our question? Since the number of eggs depends on how many hens there are

Thank you for your pointing out! Sure, If that is the case, we could create a new column = number of eggs / number of hens. Is it what you mean for the proportion? I would modified the analysis part as soon as possible and push back to the branch. Thanks again.

**Comment by carinaya** [comment]
Hi guys, I update the infer analysis part. 1. create a new column to calculate the mean number of eggs produced by each hen, and do following inferential analysis based on this new column. Thanks @Kierst01 for pointing out 2. filter the data only including the prod_process == 'all', since cage-free is not available for hatching. 

Please kindly look over again and feel free to comment and correct me if I missed or did a mistake. Thanks.

**Comment by Kierst01** [comment]
> Hi guys, I update the infer analysis part. 1. create a new column to calculate the mean number of eggs produced by each hen, and do following inferential analysis based on this new column. Thanks @Kierst01 for pointing out 2. filter the data only including the prod_process == 'all', since cage-free is not available for hatching.
> 
> Please kindly look over again and feel free to comment and correct me if I missed or did a mistake. Thanks.

Hey, I just looked it over and just noted a few things that I think we should change for a proportion test:
- in the hypothesis tests I believe it should be p_hat instead of mu (and we would need to change the explanation for the hypothesis/observed test stat as well)
- in the permutation I believe it should be `calculate(stat  = "diff in props", ...` instead of diff in means

Otherwise I think it is good :)

**Comment by carinaya** [comment]
> > Hi guys, I update the infer analysis part. 1. create a new column to calculate the mean number of eggs produced by each hen, and do following inferential analysis based on this new column. Thanks @Kierst01 for pointing out 2. filter the data only including the prod_process == 'all', since cage-free is not available for hatching.
> > Please kindly look over again and feel free to comment and correct me if I missed or did a mistake. Thanks.
> 
> Hey, I just looked it over and just noted a few things that I think we should change for a proportion test:
> 
> * in the hypothesis tests I believe it should be p_hat instead of mu (and we would need to change the explanation for the hypothesis/observed test stat as well)
> * in the permutation I believe it should be `calculate(stat  = "diff in props", ...` instead of diff in means
> 
> Otherwise I think it is good :)

For the proportion part, I thought it is not a proportion because for proportion it means what percentage of the total belongs to one class, and the number is always between 0 and 1. In our case, we can say how many eggs produced by each hen, which is definitely greater than 1. Every hen can produce different number of eggs, we want to calculate the average number of eggs produced by each hen, which is a mean problem.

**Comment by Kierst01** [comment]
> > > Hi guys, I update the infer analysis part. 1. create a new column to calculate the mean number of eggs produced by each hen, and do following inferential analysis based on this new column. Thanks @Kierst01 for pointing out 2. filter the data only including the prod_process == 'all', since cage-free is not available for hatching.
> > > Please kindly look over again and feel free to comment and correct me if I missed or did a mistake. Thanks.
> > 
> > 
> > Hey, I just looked it over and just noted a few things that I think we should change for a proportion test:
> > 
> > * in the hypothesis tests I believe it should be p_hat instead of mu (and we would need to change the explanation for the hypothesis/observed test stat as well)
> > * in the permutation I believe it should be `calculate(stat  = "diff in props", ...` instead of diff in means
> > 
> > Otherwise I think it is good :)
> 
> For the proportion part, I thought it is not a proportion because for proportion it means what percentage of the total belongs to one class, and the number is always between 0 and 1. In our case, we can say how many eggs produced by each hen, which is definitely greater than 1. Every hen can produce different number of eggs, we want to calculate the average number of eggs produced by each hen, which is a mean problem.

Yes, you are correct! Forgot about that aspect, thanks!

**Pull request merged**
